### ISSUE TITLE
1.17.1 Crash with Fabric Loader 0.12

### ISSUE THREAD

**Issue by DatrixTHLK** [The-Fireplace-Minecraft-Mods/Annotated-DI#5]
**Describe the bug**
Crashing to desktop.

**To Reproduce**
1. Just try opening minecraft

**Logs/Screenshots/Videos**
[Crash Log ](https://gist.github.com/DatrixTHLK/18be2b3d7952499ad5ff0d148e653275)
[FML](https://gist.github.com/DatrixTHLK/a956812ff4fb87b6fc1a1e480aa650a0)

**Versions**
 - Minecraft: 1.17.1
 - Annotated DI: 2.0.3
 - Fabric API: 0.12.1

**Comment by The-Fireplace** [comment]
Looks like Fabric Loader updated some stuff that Annotated DI used. Will fix ASAP

**Comment by The-Fireplace** [comment]
Fixed with Annotated DI 2.0.4

**Comment by DatrixTHLK** [comment]
Thank you! I appreciate the response and the fix.
