### ISSUE TITLE
Incompatible with Quilt Loader due to use of net.fabricmc.loader.impl.util.UrlConversionException

### ISSUE THREAD

**Issue by Nolij** [The-Fireplace-Minecraft-Mods/Annotated-DI#9]
**Describe the bug**
The UrlUtil class provided by this mod depends on `net.fabricmc.loader.impl.util.UrlConversionException`, which doesn't exist in Quilt, and according to one of the Quilt devs should be considered volatile in Fabric as well.

Unfortunately this doesn't only make this mod incompatible with Quilt, but a handful of other popular mods which have recently migrated to Quilt only and now won't run on Fabric.

Ordinarily I'd just put in a pull request to change this given it's just an exception type I'm just concerned it will cause issues with mods which depend on this and I'm not going to clone all 50 of the fireplace mods to determine how breaking of a change that would be.

**To Reproduce**
1. Attempt to use this mod with Quilt loader

**Logs/Screenshots/Videos**
https://0x0.st/oaXp.txt

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.18.2
 - Mod Version: Whatever Fireplace Lib 6.3.1+1.18.2 or Unforgiving Void 3.1.4+1.18.2 bundles, I'm not using this mod directly
 - Fabric API: Quilted Fabric API 1.0.0-beta.14+0.51.1-1.18.2

**Comment by Nolij** [comment]
Pulled this version from logs: 2.1.0+1.18.2

**Comment by The-Fireplace** [comment]
The next major version is in the works, I'll be sure this is fixed with it.

**Comment by Nolij** [comment]
> The next major version is in the works, I'll be sure this is fixed with it.

If that's a long ways off I'd like to use Unforgiving Void in a modpack I'll be starting very soon so I'd appreciate it if you hotfix the release version.

**Comment by The-Fireplace** [comment]
I'm working out the last of the issues with it now, Annotated DI and Fireplace Lib are both nearly ready. This is a breaking release as it also restructures some things in a way that allows Forge compatibility, so I will also have to update Unforgiving Void after that. In any event, if all goes smoothly it shouldn't be too terribly long.

**Comment by The-Fireplace** [comment]
Fixed in Annotated DI 3.0.0

**Comment by The-Fireplace** [comment]
Unforgiving Void has been updated to use Annotated DI 4 / Fireplace Lib 7. Enjoy!
